version: '3.8'
services:
  airflow-webserver:
    image: apache/airflow:2.4.0
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__WEBSERVER__SECRET_KEY=your_secret_key
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/usr/local/airflow/dags
